### ISSUE TITLE
Possibly incorrect EOMs

### ISSUE THREAD

**Issue by jmichaux** [jnez71/AcroCart#1]
Do you have a quick and error-free way to move the equations of motion from sympy to numpy?  I've been going through the [derive_acrocart](https://github.com/jnez71/AcroCart/blob/master/derive_acrocart) script and I'm a little confused. The potential energy equation shouldn't contain a term for the cart because it is fixed to the track.  The kinetic energy equations also seem to be missing terms.  Since each rod is rotating about the joints, the [Parallel Axis Theorem](https://en.wikipedia.org/wiki/Parallel_axis_theorem) says that the inertial term should either be `I1 = (m1/3)*l1**2` or `I1 =  (m1/12)*l1**2 + m1*(l1/2)**2 `.

I'd like to try the new equations of motion.  But right now my method of replacing the equations in the [dynamics](https://github.com/jnez71/AcroCart/blob/master/acrocart/dynamics.py) file is pretty error prone.

**Comment by jmichaux** [comment]
It turns out that I am probably wrong...but I'd still be interested in knowing if you have an easy way of turning the equations into usable numpy arrays.

**Comment by jnez71** [comment]
The variable `y0` has value `0` (line 38) so indeed the cart does not add to the potential energy in line 57. For the kinetic energy terms, the parallel axis theorem does not apply; each body has rotational kinetic energy proportional to its *own* moment of inertia about its *own* center-of-mass. See this derivation of the double pendulum to verify:
https://en.wikipedia.org/wiki/Double_pendulum#Lagrangian

Sorry about this, but currently the only way to take the equations of motion over from derive_acrocart to the solver code is by copy paste.
